#!/usr/bin/env python
import rospy
import os
import time

from std_msgs.msg import Bool, Empty
from std_srvs import srv
from ros_jetson_stats.srv import fan


def rebootCallback(x):
    rospy.loginfo("Reboot command invoked")
    time.sleep(1)
    os.system("shutdown -r now")

def preshutdownCallback(x):
    rospy.loginfo("pre-shutdown command invoked")
    relay1_pub = rospy.Publisher("relay1", Bool, queue_size=1)
    relay2_pub = rospy.Publisher("relay2", Bool, queue_size=1)
    relay_msg = Bool()
    relay_msg.data = True
    relay1_pub.publish(relay_msg)
    relay2_pub.publish(relay_msg)
    try:
        rospy.wait_for_service("/ros_jetson_stats/fan", 2)
        fan_srv = rospy.ServiceProxy("/ros_jetson_stats/fan", fan)
        msg = fan()
        msg.mode = "manual"
        msg.fanSpeed = 0
        resp = fan_srv(msg)
    except rospy.ROSException as e:
        rospy.logerr(e)
    try:
        rospy.wait_for_service('/stop_motor', 2)
        stop_motor = rospy.ServiceProxy('/stop_motor', srv.Empty)
        resp = stop_motor(srv.EmptyRequest())
    except rospy.ROSException as e:
        rospy.logerr(e)
    shutdown_pub = rospy.Publisher("system/shutdown", Empty, queue_size=5)
    # shutdown_pub.publish(Empty())

def shutdownCallback(x):
    rospy.loginfo("Shutdown command invoked")
    time.sleep(1)
    os.system("shutdown -h now")

try:
    rospy.init_node("leo_system_jetson")
    preshutdown_pub = rospy.Subscriber("system/preshutdown", Empty, preshutdownCallback)
    shutdown_pub = rospy.Subscriber("system/shutdown", Empty, shutdownCallback)
    rospy.loginfo("Jetson system node started!")
except rospy.ROSInterruptException as e:
    rospy.logerr(e)

rospy.spin()